### ISSUE TITLE
TVDB artwork script is broken

### ISSUE THREAD

**Issue by SHJordan** [filebot/scripts#51] opened 2018-09-16 15:46 UTC
scripts/artwork.tvdb.groovy since TVDB changed it layout it no longer can fetch posters and other goodies. Can you take a look @rednoah ?

**Comment by SHJordan** [comment] 2018-09-16 15:49
example: Attack on Titan - Main folder
![image](https://user-images.githubusercontent.com/884602/45598230-dabbf800-b9ae-11e8-91fc-a90112d3c1cb.png)
Season Folder:
![image](https://user-images.githubusercontent.com/884602/45598233-eefff500-b9ae-11e8-970c-c4d9a956eade.png)

**Comment by SHJordan** [comment] 2018-09-16 15:50
cmd info:
![image](https://user-images.githubusercontent.com/884602/45598247-24a4de00-b9af-11e8-86ea-5c7b6ebebfe2.png)

**Comment by SHJordan** [comment] 2018-09-16 15:52
It is filling not found stuff with 0 bytes placeholder images.

**Comment by SHJordan** [comment] 2018-09-16 15:56
https://www.thetvdb.com/series/attack-on-titan have all the banners, posters etc, i think they just changed where it is stored.

**Comment by SHJordan** [comment] 2018-09-16 15:58
If you can, add a optional parameter to set the lang of the series, like --lang ptb (portuguese brazilian)

**Comment by rednoah** [comment] 2018-09-19 14:40
Please run `filebot -script fn:sysinfo` and post the output.

**Comment by rednoah** [comment] 2018-09-19 14:42
Isn't `--lang` already supported to generate nfo / artwork with different language preferences?

**Comment by SHJordan** [comment] 2018-09-19 22:36
> 
> 
> Are you using the latest release? Please run `filebot -script fn:sysinfo` and post the output.

FileBot 4.8.2 (r5789)
JNA Native: 5.1.0
MediaInfo: 0.7.93
7-Zip-JBinding: 9.20
Chromaprint: 1.4.2
Extended Attributes: OK
Unicode Filesystem: OK
Script Bundle: 2018-03-16 (r516)
Groovy: 2.4.10
JRE: Java(TM) SE Runtime Environment 1.8.0_181
JVM: 64-bit Java HotSpot(TM) 64-Bit Server VM
CPU/MEM: 4 Core / 3 GB Max Memory / 23 MB Used Memory
OS: Windows 10 (amd64)
Package: MSI

**Comment by rednoah** [comment] 2018-09-20 03:48
Strange indeed. I'll run a few tests and see what's going on.

**Comment by SHJordan** [comment] 2018-09-20 03:49
> 
> 
> Isn't `--lang` already supported to generate nfo / artwork with different language preferences?

seems to be working, but not on all tags.

**Comment by rednoah** [comment] 2018-09-24 04:35
Might have been temporary server-side issues.

I can't reproduce the issue on my end:
```
filebot -script fn:artwork.tmdb .
Movies/Avatar (2009) => Avatar (2009)
Generate Movie NFO: Avatar [19995]
IllegalArgumentException: Invalid media file: Movies/Avatar (2009)/Avatar (2009).mkv
Fetching Movies/Avatar (2009)/poster.jpg => [posters/1000x1500, en, 6.322, https://image.tmdb.org/t/p/original/8Ic8rRVoVrDJJlXzVzGxAesufUV.jpg]
Fetching Movies/Avatar (2009)/fanart.jpg => [backdrops/1920x1080, en, 5.172, https://image.tmdb.org/t/p/original/ldVvzRSWbs31z3IOhZZ4CxgCJAt.jpg]
Fetching Movies/Avatar (2009)/clearart.png => [hdmovieclearart, en, 11.0, https://assets.fanart.tv/fanart/movies/19995/hdmovieclearart/avatar-51a3a817f375b.png]
Fetching Movies/Avatar (2009)/logo.png => [hdmovielogo, fr, 9.0, https://assets.fanart.tv/fanart/movies/19995/hdmovielogo/avatar-51c893f5d905d.png]
Fetching Movies/Avatar (2009)/disc.png => [moviedisc/bluray, en, 8.0, https://assets.fanart.tv/fanart/movies/19995/moviedisc/avatar-5119a01b0e268.png]
Done ヾ(＠⌒ー⌒＠)ノ
```
```
tree -h
.
└── [ 128]  Movies
    └── [ 352]  Avatar\ (2009)
        ├── [   0]  Avatar\ (2009).mkv
        ├── [753K]  clearart.png
        ├── [656K]  disc.png
        ├── [176K]  fanart.jpg
        ├── [ 88K]  folder.jpg
        ├── [120K]  logo.png
        ├── [8.0K]  movie.nfo
        └── [ 88K]  poster.jpg
```

**Comment by SHJordan** [comment] 2018-09-24 18:01
> 
> 
> Might have been temporary server-side issues.
> 
> I can't reproduce the issue on my end:
> 
> ```
> filebot -script fn:artwork.tmdb .
> Movies/Avatar (2009) => Avatar (2009)
> Generate Movie NFO: Avatar [19995]
> IllegalArgumentException: Invalid media file: Movies/Avatar (2009)/Avatar (2009).mkv
> Fetching Movies/Avatar (2009)/poster.jpg => [posters/1000x1500, en, 6.322, https://image.tmdb.org/t/p/original/8Ic8rRVoVrDJJlXzVzGxAesufUV.jpg]
> Fetching Movies/Avatar (2009)/fanart.jpg => [backdrops/1920x1080, en, 5.172, https://image.tmdb.org/t/p/original/ldVvzRSWbs31z3IOhZZ4CxgCJAt.jpg]
> Fetching Movies/Avatar (2009)/clearart.png => [hdmovieclearart, en, 11.0, https://assets.fanart.tv/fanart/movies/19995/hdmovieclearart/avatar-51a3a817f375b.png]
> Fetching Movies/Avatar (2009)/logo.png => [hdmovielogo, fr, 9.0, https://assets.fanart.tv/fanart/movies/19995/hdmovielogo/avatar-51c893f5d905d.png]
> Fetching Movies/Avatar (2009)/disc.png => [moviedisc/bluray, en, 8.0, https://assets.fanart.tv/fanart/movies/19995/moviedisc/avatar-5119a01b0e268.png]
> Done ヾ(＠⌒ー⌒＠)ノ
> ```
> 
> ```
> tree -h
> .
> └── [ 128]  Movies
>     └── [ 352]  Avatar\ (2009)
>         ├── [   0]  Avatar\ (2009).mkv
>         ├── [753K]  clearart.png
>         ├── [656K]  disc.png
>         ├── [176K]  fanart.jpg
>         ├── [ 88K]  folder.jpg
>         ├── [120K]  logo.png
>         ├── [8.0K]  movie.nfo
>         └── [ 88K]  poster.jpg
> ```

That is TMDB not TVDB script, can you double check?

**Comment by SHJordan** [comment] 2018-09-24 18:59
`│
├───Attack on Titan
│   │   banner.jpg **0 bytes**
│   │   clearart.png
│   │   fanart.jpg **0 bytes**
│   │   folder.jpg **0 bytes**
│   │   landscape.jpg
│   │   logo.png
│   │   poster.jpg **0 bytes**
│   │   tvshow.nfo
│   │
│   └───Season 3
│           Ataque dos Titãs - 3x10 - Amigos.mkv
│           Attack on Titan - 3x01 - Sinal de Fumaça.mkv
│           Attack on Titan - 3x02 - Dor.mkv
│           Attack on Titan - 3x03 - História Antiga.mkv
│           Attack on Titan - 3x04 - Confiança.mkv
│           Attack on Titan - 3x05 - Resposta.mkv
│           Attack on Titan - 3x06 - Pecado.mkv
│           Attack on Titan - 3x07 - Desejo.mkv
│           Attack on Titan - 3x08 - Fora das Muralhas do Distrito de Orvud.mkv
│           Attack on Titan - 3x09 - Rei das Muralhas.mkv
│           folder.jpg **0 bytes**
│           poster.jpg **0 bytes** `

**Comment by SHJordan** [comment] 2018-09-25 15:49
Here is my testcase:

> PS C:\Users\shjor\Videos\Anime\Attack on Titan> filebot -script fn:artwork.tvdb . -non-strict --lang pob
> C:\Users\shjor\Videos\Anime\Attack on Titan\Season 3 => Search by Ataque dos Titãs
> C:\Users\shjor\Videos\Anime\Attack on Titan\Season 3 => Ataque dos Titãs
> Generate Series NFO: Ataque dos Titãs [267440]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\poster.jpg => [poster/680x1000, en, 6.6, http://thetvdb.com/banners/posters/267440-20.jpg]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\banner.jpg => [series/graphical, en, 7.8125, http://thetvdb.com/banners/graphical/267440-g.jpg]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\fanart.jpg => [fanart/1920x1080, en, 10.0, http://thetvdb.com/banners/fanart/original/5b6137dc40fdb.jpg]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\Season 3\poster.jpg => [season/season/3, ja, 8.0, http://thetvdb.com/banners/seasons/267440-3.jpg]
> Banner not found: C:\Users\shjor\Videos\Anime\Attack on Titan\Season 3\banner.jpg / seasonwide:seasonwide
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\clearart.png => [hdclearart, en, 8.0, https://assets.fanart.tv/fanart/tv/267440/hdclearart/attack-on-titan-51a64c64991b3.png]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\logo.png => [hdtvlogo, en, 11.0, https://assets.fanart.tv/fanart/tv/267440/hdtvlogo/attack-on-titan-51a64c2cb7247.png]
> Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\landscape.jpg => [tvthumb, es, 3.0, https://assets.fanart.tv/fanart/tv/267440/tvthumb/attack-on-titan-590c9ec1cc507.jpg]
> Fanart not found: C:\Users\shjor\Videos\Anime\Attack on Titan\Season 3\landscape.jpg / seasonthumb
> Done ?(?????)?

**Comment by rednoah** [comment] 2018-09-26 09:59
Are you sure that you're using the latest version of FileBot?
```
Fetching C:\Users\shjor\Videos\Anime\Attack on Titan\poster.jpg => [poster/680x1000, en, 6.6, http://thetvdb.com/banners/posters/267440-20.jpg]
```
This particular case doesn't work because `http://thetvdb.com/banners/posters/267440-20.jpg` is a `http` URL, which results in a `302` redirect response, instead of the file content, thus 0 byte files. This is a known `FileBot 4.7.9` issue.

If you are running `FileBot 4.8.2` then `https` is used, resolving the issue. You may have installed multiple versions of FileBot and accidentally be running an old one. Please check. My logs show `https` being used. Yours should too.

**Closed** 2019-02-18 20:55 UTC
